### ISSUE TITLE
Error while Opening in Android Studio 

### ISSUE THREAD

**Issue by maboueita** [nenick/AndroidAppDevelopment#1]
I get 
**Local path doesn't exist. Local path doesn't exist. The project may need to be synced with Gradle files.**
while trying to open in Android Studio. Do I need to modify anything after clone?

**Comment by nenick** [comment]
No it should just work when you have the latest Android Studio and the unit test plugin installed. Have you some more informations for me? Looks like this issue is known for Android Studio. https://code.google.com/p/android/issues/detail?id=77523 I never saw this issue.

**Comment by lawrencewqy** [comment]
I get the same error when i try to run App on my device,and there is not an apk generated in build/outputs/apk deirectory

**Comment by nenick** [comment]
Please help me to reproduce this issue. Which Android Studio version use you? What are your steps? Works for you when you use the command-line?

**Comment by lawrencewqy** [comment]
I use the latest Android Studio 1.1 beta 4 , and I just open in android studio and run App.
I try to use the command-line  but i get the exception:
xUNEXPECTED TOP-LEVEL EXCEPTION:  
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.processClass(Main.java:704)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
        at com.android.dx.command.dexer.Main.access$300(Main.java:82)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:632)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
        at com.android.dx.command.dexer.Main.run(Main.java:245)
        at com.android.dx.command.dexer.Main.main(Main.java:214)
        at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/example/data/repository/UserRepository$UserDetailsCallback.class

1 error; aborting                

UNEXPECTED TOP-LEVEL EXCEPTION:  
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.processClass(Main.java:704)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
        at com.android.dx.command.dexer.Main.access$300(Main.java:82)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:632)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
        at com.android.dx.command.dexer.Main.run(Main.java:245)
        at com.android.dx.command.dexer.Main.main(Main.java:214)
        at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/example/shared/dagger/DaggerSupport.class

1 error; aborting  
:App:preDexDebug FAILED          

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':App:preDexDebug'.
  
  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  >     /Users/lawrence/Documents/androiddev/sdk/build-tools/21.1.1/dx --dex --output /Users/lawrence/GitHub/AndroidAppDevelopment/App/build/intermediates/pre-dexed/debug/DataRepository-557f543dfeb8f9632badef1f214e8e3c1c0bad54.jar /Users/lawrence/GitHub/AndroidAppDevelopment/DataRepository/build/libs/DataRepository.jar
  > Error Code: 
  >       1  
  > Output:     
  
  ```
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
            at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
            at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
            at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
            at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
            at com.android.dx.command.dexer.Main.processClass(Main.java:704)
            at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
            at com.android.dx.command.dexer.Main.access$300(Main.java:82)
            at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
            at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
            at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
            at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
            at com.android.dx.command.dexer.Main.processOne(Main.java:632)
            at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
            at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
            at com.android.dx.command.dexer.Main.run(Main.java:245)
            at com.android.dx.command.dexer.Main.main(Main.java:214)
            at com.android.dx.command.Main.main(Main.java:106)
    ...while parsing com/example/data/repository/UserRepository$UserDetailsCallback.class
  
    1 error; aborting
  ```
- Try:  
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by nenick** [comment]
Do you use Java 8? Please try using Java 7 maybe this could be the issue. Someone else reported this at http://stackoverflow.com/questions/24662801/bad-class-file-magic-or-version

**Comment by lawrencewqy** [comment]
That's right,i switch to java 7 and it works,thank you very much!

**Comment by nenick** [comment]
Thank you for your help to find the cause.

If you like you could try https://github.com/nenick/AndroidStudioAndRobolectric with java 8 and give me feedback ;)
